resolver: lts-18.18
packages:
- './unicode-data-core'
- './unicode-data-names'
- './unicode-data-scripts'
- './unicode-data-security'
- './experimental/unicode-data-text'
extra-deps:
- streamly-0.8.0
flags:
  mintty:
    Win32-2-13-1: false
