-- DO NOT EDIT MANUALLY: autogenerated by ucd2haskell
{-# OPTIONS_HADDOCK hide #-}

-- |
-- Module      : Unicode.Internal.Char.Version
-- Copyright   : (c) 2024 Composewell Technologies and Contributors
-- License     : Apache-2.0
-- Maintainer  : streamly@composewell.com
-- Stability   : experimental

module Unicode.Internal.Char.Version (unicodeVersion) where

import Data.Version (Version, makeVersion)

-- | Version of the Unicode standard used by this package:
-- [16.0.0](https://www.unicode.org/versions/Unicode16.0.0/).
--
-- @since 0.3.0
unicodeVersion :: Version
unicodeVersion = makeVersion [16,0,0]
