-- autogenerated from https://www.unicode.org/Public/15.0.0/ucd/NameAliases.txt
-- |
-- Module      : Unicode.Internal.Char.UnicodeData.NameAliases
-- Copyright   : (c) 2022 Composewell Technologies and Contributors
-- License     : Apache-2.0
-- Maintainer  : streamly@composewell.com
-- Stability   : experimental

{-# OPTIONS_HADDOCK hide #-}

module Unicode.Internal.Char.UnicodeData.NameAliases
(NameAliasType(..), maxNameAliasType, nameAliases)
where

import Data.Ix (Ix)
import GHC.Exts (Addr#, Char#)

-- | Type of name alias. See Unicode Standard 15.0.0, section 4.8.
--
-- @since 0.1.0
data NameAliasType
    = Correction
    -- ^ Corrections for serious problems in the character names.
    | Control
    -- ^ ISO&#xa0;6429 names for @C0@ and @C1@ control functions, and other
    --   commonly occurring names for control codes.
    | Alternate
    -- ^ A few widely used alternate names for format characters.
    | Figment
    -- ^ Several documented labels for @C1@ control code points which
    --   were never actually approved in any standard.
    | Abbreviation
    -- ^ Commonly occurring abbreviations (or acronyms) for control codes,
    --   format characters, spaces, and variation selectors.
    deriving (Enum, Bounded, Eq, Ord, Ix, Show)

-- | >>> maxNameAliasType == fromEnum (maxBound :: NameAliasType)
maxNameAliasType :: Int
maxNameAliasType = 4

-- | Detailed character names aliases.
-- The names are listed in the original order of the UCD.
--
-- See 'nameAliases' if the alias type is not required.
--
-- @since 0.1.0
nameAliases :: Char# -> Addr#
nameAliases = \case
  '\x0000'# -> "\0\5\0\0\11\0NULL\0\0NUL\0"#
  '\x0001'# -> "\0\5\0\0\23\0START OF HEADING\0\0SOH\0"#
  '\x0002'# -> "\0\5\0\0\20\0START OF TEXT\0\0STX\0"#
  '\x0003'# -> "\0\5\0\0\18\0END OF TEXT\0\0ETX\0"#
  '\x0004'# -> "\0\5\0\0\26\0END OF TRANSMISSION\0\0EOT\0"#
  '\x0005'# -> "\0\5\0\0\14\0ENQUIRY\0\0ENQ\0"#
  '\x0006'# -> "\0\5\0\0\18\0ACKNOWLEDGE\0\0ACK\0"#
  '\x0007'# -> "\0\5\0\0\12\0ALERT\0\0BEL\0"#
  '\x0008'# -> "\0\5\0\0\16\0BACKSPACE\0\0BS\0"#
  '\x0009'# -> "\0\5\0\0\50\27CHARACTER TABULATION\0\0HORIZONTAL TABULATION\0\54HT\0\0TAB\0"#
  '\x000A'# -> "\0\5\0\0\39\16LINE FEED\0\26NEW LINE\0\0END OF LINE\0\43LF\0\47NL\0\0EOL\0"#
  '\x000B'# -> "\0\5\0\0\43\22LINE TABULATION\0\0VERTICAL TABULATION\0\0VT\0"#
  '\x000C'# -> "\0\5\0\0\16\0FORM FEED\0\0FF\0"#
  '\x000D'# -> "\0\5\0\0\22\0CARRIAGE RETURN\0\0CR\0"#
  '\x000E'# -> "\0\5\0\0\35\16SHIFT OUT\0\0LOCKING-SHIFT ONE\0\0SO\0"#
  '\x000F'# -> "\0\5\0\0\35\15SHIFT IN\0\0LOCKING-SHIFT ZERO\0\0SI\0"#
  '\x0010'# -> "\0\5\0\0\23\0DATA LINK ESCAPE\0\0DLE\0"#
  '\x0011'# -> "\0\5\0\0\25\0DEVICE CONTROL ONE\0\0DC1\0"#
  '\x0012'# -> "\0\5\0\0\25\0DEVICE CONTROL TWO\0\0DC2\0"#
  '\x0013'# -> "\0\5\0\0\27\0DEVICE CONTROL THREE\0\0DC3\0"#
  '\x0014'# -> "\0\5\0\0\26\0DEVICE CONTROL FOUR\0\0DC4\0"#
  '\x0015'# -> "\0\5\0\0\27\0NEGATIVE ACKNOWLEDGE\0\0NAK\0"#
  '\x0016'# -> "\0\5\0\0\23\0SYNCHRONOUS IDLE\0\0SYN\0"#
  '\x0017'# -> "\0\5\0\0\32\0END OF TRANSMISSION BLOCK\0\0ETB\0"#
  '\x0018'# -> "\0\5\0\0\13\0CANCEL\0\0CAN\0"#
  '\x0019'# -> "\0\5\0\0\20\0END OF MEDIUM\0\25EOM\0\0EM\0"#
  '\x001A'# -> "\0\5\0\0\17\0SUBSTITUTE\0\0SUB\0"#
  '\x001B'# -> "\0\5\0\0\13\0ESCAPE\0\0ESC\0"#
  '\x001C'# -> "\0\5\0\0\49\33INFORMATION SEPARATOR FOUR\0\0FILE SEPARATOR\0\0FS\0"#
  '\x001D'# -> "\0\5\0\0\51\34INFORMATION SEPARATOR THREE\0\0GROUP SEPARATOR\0\0GS\0"#
  '\x001E'# -> "\0\5\0\0\50\32INFORMATION SEPARATOR TWO\0\0RECORD SEPARATOR\0\0RS\0"#
  '\x001F'# -> "\0\5\0\0\48\32INFORMATION SEPARATOR ONE\0\0UNIT SEPARATOR\0\0US\0"#
  '\x0020'# -> "\0\0\0\0\5\0SP\0"#
  '\x007F'# -> "\0\5\0\0\13\0DELETE\0\0DEL\0"#
  '\x0080'# -> "\0\0\0\5\24\0PADDING CHARACTER\0\0PAD\0"#
  '\x0081'# -> "\0\0\0\5\24\0HIGH OCTET PRESET\0\0HOP\0"#
  '\x0082'# -> "\0\5\0\0\27\0BREAK PERMITTED HERE\0\0BPH\0"#
  '\x0083'# -> "\0\5\0\0\20\0NO BREAK HERE\0\0NBH\0"#
  '\x0084'# -> "\0\5\0\0\12\0INDEX\0\0IND\0"#
  '\x0085'# -> "\0\5\0\0\16\0NEXT LINE\0\0NEL\0"#
  '\x0086'# -> "\0\5\0\0\29\0START OF SELECTED AREA\0\0SSA\0"#
  '\x0087'# -> "\0\5\0\0\27\0END OF SELECTED AREA\0\0ESA\0"#
  '\x0088'# -> "\0\5\0\0\58\31CHARACTER TABULATION SET\0\0HORIZONTAL TABULATION SET\0\0HTS\0"#
  '\x0089'# -> "\0\5\0\0\88\46CHARACTER TABULATION WITH JUSTIFICATION\0\0HORIZONTAL TABULATION WITH JUSTIFICATION\0\0HTJ\0"#
  '\x008A'# -> "\0\5\0\0\51\26LINE TABULATION SET\0\0VERTICAL TABULATION SET\0\0VTS\0"#
  '\x008B'# -> "\0\5\0\0\46\27PARTIAL LINE FORWARD\0\0PARTIAL LINE DOWN\0\0PLD\0"#
  '\x008C'# -> "\0\5\0\0\45\28PARTIAL LINE BACKWARD\0\0PARTIAL LINE UP\0\0PLU\0"#
  '\x008D'# -> "\0\5\0\0\39\24REVERSE LINE FEED\0\0REVERSE INDEX\0\0RI\0"#
  '\x008E'# -> "\0\5\0\0\39\23SINGLE SHIFT TWO\0\0SINGLE-SHIFT-2\0\0SS2\0"#
  '\x008F'# -> "\0\5\0\0\41\25SINGLE SHIFT THREE\0\0SINGLE-SHIFT-3\0\0SS3\0"#
  '\x0090'# -> "\0\5\0\0\28\0DEVICE CONTROL STRING\0\0DCS\0"#
  '\x0091'# -> "\0\5\0\0\37\22PRIVATE USE ONE\0\0PRIVATE USE-1\0\0PU1\0"#
  '\x0092'# -> "\0\5\0\0\37\22PRIVATE USE TWO\0\0PRIVATE USE-2\0\0PU2\0"#
  '\x0093'# -> "\0\5\0\0\25\0SET TRANSMIT STATE\0\0STS\0"#
  '\x0094'# -> "\0\5\0\0\23\0CANCEL CHARACTER\0\0CCH\0"#
  '\x0095'# -> "\0\5\0\0\22\0MESSAGE WAITING\0\0MW\0"#
  '\x0096'# -> "\0\5\0\0\53\28START OF GUARDED AREA\0\0START OF PROTECTED AREA\0\0SPA\0"#
  '\x0097'# -> "\0\5\0\0\49\26END OF GUARDED AREA\0\0END OF PROTECTED AREA\0\0EPA\0"#
  '\x0098'# -> "\0\5\0\0\22\0START OF STRING\0\0SOS\0"#
  '\x0099'# -> "\0\0\0\5\42\0SINGLE GRAPHIC CHARACTER INTRODUCER\0\0SGC\0"#
  '\x009A'# -> "\0\5\0\0\34\0SINGLE CHARACTER INTRODUCER\0\0SCI\0"#
  '\x009B'# -> "\0\5\0\0\34\0CONTROL SEQUENCE INTRODUCER\0\0CSI\0"#
  '\x009C'# -> "\0\5\0\0\24\0STRING TERMINATOR\0\0ST\0"#
  '\x009D'# -> "\0\5\0\0\31\0OPERATING SYSTEM COMMAND\0\0OSC\0"#
  '\x009E'# -> "\0\5\0\0\22\0PRIVACY MESSAGE\0\0PM\0"#
  '\x009F'# -> "\0\5\0\0\34\0APPLICATION PROGRAM COMMAND\0\0APC\0"#
  '\x00A0'# -> "\0\0\0\0\5\0NBSP\0"#
  '\x00AD'# -> "\0\0\0\0\5\0SHY\0"#
  '\x01A2'# -> "\5\0\0\0\0\0LATIN CAPITAL LETTER GHA\0"#
  '\x01A3'# -> "\5\0\0\0\0\0LATIN SMALL LETTER GHA\0"#
  '\x034F'# -> "\0\0\0\0\5\0CGJ\0"#
  '\x0616'# -> "\5\0\0\0\0\0ARABIC SMALL HIGH LIGATURE ALEF WITH YEH BARREE\0"#
  '\x061C'# -> "\0\0\0\0\5\0ALM\0"#
  '\x0709'# -> "\5\0\0\0\0\0SYRIAC SUBLINEAR COLON SKEWED LEFT\0"#
  '\x0CDE'# -> "\5\0\0\0\0\0KANNADA LETTER LLLA\0"#
  '\x0E9D'# -> "\5\0\0\0\0\0LAO LETTER FO FON\0"#
  '\x0E9F'# -> "\5\0\0\0\0\0LAO LETTER FO FAY\0"#
  '\x0EA3'# -> "\5\0\0\0\0\0LAO LETTER RO\0"#
  '\x0EA5'# -> "\5\0\0\0\0\0LAO LETTER LO\0"#
  '\x0FD0'# -> "\5\0\0\0\0\0TIBETAN MARK BKA- SHOG GI MGO RGYAN\0"#
  '\x11EC'# -> "\5\0\0\0\0\0HANGUL JONGSEONG YESIEUNG-KIYEOK\0"#
  '\x11ED'# -> "\5\0\0\0\0\0HANGUL JONGSEONG YESIEUNG-SSANGKIYEOK\0"#
  '\x11EE'# -> "\5\0\0\0\0\0HANGUL JONGSEONG SSANGYESIEUNG\0"#
  '\x11EF'# -> "\5\0\0\0\0\0HANGUL JONGSEONG YESIEUNG-KHIEUKH\0"#
  '\x180B'# -> "\0\0\0\0\5\0FVS1\0"#
  '\x180C'# -> "\0\0\0\0\5\0FVS2\0"#
  '\x180D'# -> "\0\0\0\0\5\0FVS3\0"#
  '\x180E'# -> "\0\0\0\0\5\0MVS\0"#
  '\x180F'# -> "\0\0\0\0\5\0FVS4\0"#
  '\x1BBD'# -> "\5\0\0\0\0\0SUNDANESE LETTER ARCHAIC I\0"#
  '\x200B'# -> "\0\0\0\0\5\0ZWSP\0"#
  '\x200C'# -> "\0\0\0\0\5\0ZWNJ\0"#
  '\x200D'# -> "\0\0\0\0\5\0ZWJ\0"#
  '\x200E'# -> "\0\0\0\0\5\0LRM\0"#
  '\x200F'# -> "\0\0\0\0\5\0RLM\0"#
  '\x202A'# -> "\0\0\0\0\5\0LRE\0"#
  '\x202B'# -> "\0\0\0\0\5\0RLE\0"#
  '\x202C'# -> "\0\0\0\0\5\0PDF\0"#
  '\x202D'# -> "\0\0\0\0\5\0LRO\0"#
  '\x202E'# -> "\0\0\0\0\5\0RLO\0"#
  '\x202F'# -> "\0\0\0\0\5\0NNBSP\0"#
  '\x205F'# -> "\0\0\0\0\5\0MMSP\0"#
  '\x2060'# -> "\0\0\0\0\5\0WJ\0"#
  '\x2066'# -> "\0\0\0\0\5\0LRI\0"#
  '\x2067'# -> "\0\0\0\0\5\0RLI\0"#
  '\x2068'# -> "\0\0\0\0\5\0FSI\0"#
  '\x2069'# -> "\0\0\0\0\5\0PDI\0"#
  '\x2118'# -> "\5\0\0\0\0\0WEIERSTRASS ELLIPTIC FUNCTION\0"#
  '\x2448'# -> "\5\0\0\0\0\0MICR ON US SYMBOL\0"#
  '\x2449'# -> "\5\0\0\0\0\0MICR DASH SYMBOL\0"#
  '\x2B7A'# -> "\5\0\0\0\0\0LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE\0"#
  '\x2B7C'# -> "\5\0\0\0\0\0RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE\0"#
  '\xA015'# -> "\5\0\0\0\0\0YI SYLLABLE ITERATION MARK\0"#
  '\xAA6E'# -> "\5\0\0\0\0\0MYANMAR LETTER KHAMTI LLA\0"#
  '\xFE00'# -> "\0\0\0\0\5\0VS1\0"#
  '\xFE01'# -> "\0\0\0\0\5\0VS2\0"#
  '\xFE02'# -> "\0\0\0\0\5\0VS3\0"#
  '\xFE03'# -> "\0\0\0\0\5\0VS4\0"#
  '\xFE04'# -> "\0\0\0\0\5\0VS5\0"#
  '\xFE05'# -> "\0\0\0\0\5\0VS6\0"#
  '\xFE06'# -> "\0\0\0\0\5\0VS7\0"#
  '\xFE07'# -> "\0\0\0\0\5\0VS8\0"#
  '\xFE08'# -> "\0\0\0\0\5\0VS9\0"#
  '\xFE09'# -> "\0\0\0\0\5\0VS10\0"#
  '\xFE0A'# -> "\0\0\0\0\5\0VS11\0"#
  '\xFE0B'# -> "\0\0\0\0\5\0VS12\0"#
  '\xFE0C'# -> "\0\0\0\0\5\0VS13\0"#
  '\xFE0D'# -> "\0\0\0\0\5\0VS14\0"#
  '\xFE0E'# -> "\0\0\0\0\5\0VS15\0"#
  '\xFE0F'# -> "\0\0\0\0\5\0VS16\0"#
  '\xFE18'# -> "\5\0\0\0\0\0PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET\0"#
  '\xFEFF'# -> "\0\0\5\0\22\0BYTE ORDER MARK\0\27BOM\0\0ZWNBSP\0"#
  '\x122D4'# -> "\5\0\0\0\0\0CUNEIFORM SIGN NU11 TENU\0"#
  '\x122D5'# -> "\5\0\0\0\0\0CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR\0"#
  '\x16E56'# -> "\5\0\0\0\0\0MEDEFAIDRIN CAPITAL LETTER H\0"#
  '\x16E57'# -> "\5\0\0\0\0\0MEDEFAIDRIN CAPITAL LETTER NG\0"#
  '\x16E76'# -> "\5\0\0\0\0\0MEDEFAIDRIN SMALL LETTER H\0"#
  '\x16E77'# -> "\5\0\0\0\0\0MEDEFAIDRIN SMALL LETTER NG\0"#
  '\x1B001'# -> "\5\0\0\0\0\0HENTAIGANA LETTER E-1\0"#
  '\x1D0C5'# -> "\5\0\0\0\0\0BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS\0"#
  '\xE0100'# -> "\0\0\0\0\5\0VS17\0"#
  '\xE0101'# -> "\0\0\0\0\5\0VS18\0"#
  '\xE0102'# -> "\0\0\0\0\5\0VS19\0"#
  '\xE0103'# -> "\0\0\0\0\5\0VS20\0"#
  '\xE0104'# -> "\0\0\0\0\5\0VS21\0"#
  '\xE0105'# -> "\0\0\0\0\5\0VS22\0"#
  '\xE0106'# -> "\0\0\0\0\5\0VS23\0"#
  '\xE0107'# -> "\0\0\0\0\5\0VS24\0"#
  '\xE0108'# -> "\0\0\0\0\5\0VS25\0"#
  '\xE0109'# -> "\0\0\0\0\5\0VS26\0"#
  '\xE010A'# -> "\0\0\0\0\5\0VS27\0"#
  '\xE010B'# -> "\0\0\0\0\5\0VS28\0"#
  '\xE010C'# -> "\0\0\0\0\5\0VS29\0"#
  '\xE010D'# -> "\0\0\0\0\5\0VS30\0"#
  '\xE010E'# -> "\0\0\0\0\5\0VS31\0"#
  '\xE010F'# -> "\0\0\0\0\5\0VS32\0"#
  '\xE0110'# -> "\0\0\0\0\5\0VS33\0"#
  '\xE0111'# -> "\0\0\0\0\5\0VS34\0"#
  '\xE0112'# -> "\0\0\0\0\5\0VS35\0"#
  '\xE0113'# -> "\0\0\0\0\5\0VS36\0"#
  '\xE0114'# -> "\0\0\0\0\5\0VS37\0"#
  '\xE0115'# -> "\0\0\0\0\5\0VS38\0"#
  '\xE0116'# -> "\0\0\0\0\5\0VS39\0"#
  '\xE0117'# -> "\0\0\0\0\5\0VS40\0"#
  '\xE0118'# -> "\0\0\0\0\5\0VS41\0"#
  '\xE0119'# -> "\0\0\0\0\5\0VS42\0"#
  '\xE011A'# -> "\0\0\0\0\5\0VS43\0"#
  '\xE011B'# -> "\0\0\0\0\5\0VS44\0"#
  '\xE011C'# -> "\0\0\0\0\5\0VS45\0"#
  '\xE011D'# -> "\0\0\0\0\5\0VS46\0"#
  '\xE011E'# -> "\0\0\0\0\5\0VS47\0"#
  '\xE011F'# -> "\0\0\0\0\5\0VS48\0"#
  '\xE0120'# -> "\0\0\0\0\5\0VS49\0"#
  '\xE0121'# -> "\0\0\0\0\5\0VS50\0"#
  '\xE0122'# -> "\0\0\0\0\5\0VS51\0"#
  '\xE0123'# -> "\0\0\0\0\5\0VS52\0"#
  '\xE0124'# -> "\0\0\0\0\5\0VS53\0"#
  '\xE0125'# -> "\0\0\0\0\5\0VS54\0"#
  '\xE0126'# -> "\0\0\0\0\5\0VS55\0"#
  '\xE0127'# -> "\0\0\0\0\5\0VS56\0"#
  '\xE0128'# -> "\0\0\0\0\5\0VS57\0"#
  '\xE0129'# -> "\0\0\0\0\5\0VS58\0"#
  '\xE012A'# -> "\0\0\0\0\5\0VS59\0"#
  '\xE012B'# -> "\0\0\0\0\5\0VS60\0"#
  '\xE012C'# -> "\0\0\0\0\5\0VS61\0"#
  '\xE012D'# -> "\0\0\0\0\5\0VS62\0"#
  '\xE012E'# -> "\0\0\0\0\5\0VS63\0"#
  '\xE012F'# -> "\0\0\0\0\5\0VS64\0"#
  '\xE0130'# -> "\0\0\0\0\5\0VS65\0"#
  '\xE0131'# -> "\0\0\0\0\5\0VS66\0"#
  '\xE0132'# -> "\0\0\0\0\5\0VS67\0"#
  '\xE0133'# -> "\0\0\0\0\5\0VS68\0"#
  '\xE0134'# -> "\0\0\0\0\5\0VS69\0"#
  '\xE0135'# -> "\0\0\0\0\5\0VS70\0"#
  '\xE0136'# -> "\0\0\0\0\5\0VS71\0"#
  '\xE0137'# -> "\0\0\0\0\5\0VS72\0"#
  '\xE0138'# -> "\0\0\0\0\5\0VS73\0"#
  '\xE0139'# -> "\0\0\0\0\5\0VS74\0"#
  '\xE013A'# -> "\0\0\0\0\5\0VS75\0"#
  '\xE013B'# -> "\0\0\0\0\5\0VS76\0"#
  '\xE013C'# -> "\0\0\0\0\5\0VS77\0"#
  '\xE013D'# -> "\0\0\0\0\5\0VS78\0"#
  '\xE013E'# -> "\0\0\0\0\5\0VS79\0"#
  '\xE013F'# -> "\0\0\0\0\5\0VS80\0"#
  '\xE0140'# -> "\0\0\0\0\5\0VS81\0"#
  '\xE0141'# -> "\0\0\0\0\5\0VS82\0"#
  '\xE0142'# -> "\0\0\0\0\5\0VS83\0"#
  '\xE0143'# -> "\0\0\0\0\5\0VS84\0"#
  '\xE0144'# -> "\0\0\0\0\5\0VS85\0"#
  '\xE0145'# -> "\0\0\0\0\5\0VS86\0"#
  '\xE0146'# -> "\0\0\0\0\5\0VS87\0"#
  '\xE0147'# -> "\0\0\0\0\5\0VS88\0"#
  '\xE0148'# -> "\0\0\0\0\5\0VS89\0"#
  '\xE0149'# -> "\0\0\0\0\5\0VS90\0"#
  '\xE014A'# -> "\0\0\0\0\5\0VS91\0"#
  '\xE014B'# -> "\0\0\0\0\5\0VS92\0"#
  '\xE014C'# -> "\0\0\0\0\5\0VS93\0"#
  '\xE014D'# -> "\0\0\0\0\5\0VS94\0"#
  '\xE014E'# -> "\0\0\0\0\5\0VS95\0"#
  '\xE014F'# -> "\0\0\0\0\5\0VS96\0"#
  '\xE0150'# -> "\0\0\0\0\5\0VS97\0"#
  '\xE0151'# -> "\0\0\0\0\5\0VS98\0"#
  '\xE0152'# -> "\0\0\0\0\5\0VS99\0"#
  '\xE0153'# -> "\0\0\0\0\5\0VS100\0"#
  '\xE0154'# -> "\0\0\0\0\5\0VS101\0"#
  '\xE0155'# -> "\0\0\0\0\5\0VS102\0"#
  '\xE0156'# -> "\0\0\0\0\5\0VS103\0"#
  '\xE0157'# -> "\0\0\0\0\5\0VS104\0"#
  '\xE0158'# -> "\0\0\0\0\5\0VS105\0"#
  '\xE0159'# -> "\0\0\0\0\5\0VS106\0"#
  '\xE015A'# -> "\0\0\0\0\5\0VS107\0"#
  '\xE015B'# -> "\0\0\0\0\5\0VS108\0"#
  '\xE015C'# -> "\0\0\0\0\5\0VS109\0"#
  '\xE015D'# -> "\0\0\0\0\5\0VS110\0"#
  '\xE015E'# -> "\0\0\0\0\5\0VS111\0"#
  '\xE015F'# -> "\0\0\0\0\5\0VS112\0"#
  '\xE0160'# -> "\0\0\0\0\5\0VS113\0"#
  '\xE0161'# -> "\0\0\0\0\5\0VS114\0"#
  '\xE0162'# -> "\0\0\0\0\5\0VS115\0"#
  '\xE0163'# -> "\0\0\0\0\5\0VS116\0"#
  '\xE0164'# -> "\0\0\0\0\5\0VS117\0"#
  '\xE0165'# -> "\0\0\0\0\5\0VS118\0"#
  '\xE0166'# -> "\0\0\0\0\5\0VS119\0"#
  '\xE0167'# -> "\0\0\0\0\5\0VS120\0"#
  '\xE0168'# -> "\0\0\0\0\5\0VS121\0"#
  '\xE0169'# -> "\0\0\0\0\5\0VS122\0"#
  '\xE016A'# -> "\0\0\0\0\5\0VS123\0"#
  '\xE016B'# -> "\0\0\0\0\5\0VS124\0"#
  '\xE016C'# -> "\0\0\0\0\5\0VS125\0"#
  '\xE016D'# -> "\0\0\0\0\5\0VS126\0"#
  '\xE016E'# -> "\0\0\0\0\5\0VS127\0"#
  '\xE016F'# -> "\0\0\0\0\5\0VS128\0"#
  '\xE0170'# -> "\0\0\0\0\5\0VS129\0"#
  '\xE0171'# -> "\0\0\0\0\5\0VS130\0"#
  '\xE0172'# -> "\0\0\0\0\5\0VS131\0"#
  '\xE0173'# -> "\0\0\0\0\5\0VS132\0"#
  '\xE0174'# -> "\0\0\0\0\5\0VS133\0"#
  '\xE0175'# -> "\0\0\0\0\5\0VS134\0"#
  '\xE0176'# -> "\0\0\0\0\5\0VS135\0"#
  '\xE0177'# -> "\0\0\0\0\5\0VS136\0"#
  '\xE0178'# -> "\0\0\0\0\5\0VS137\0"#
  '\xE0179'# -> "\0\0\0\0\5\0VS138\0"#
  '\xE017A'# -> "\0\0\0\0\5\0VS139\0"#
  '\xE017B'# -> "\0\0\0\0\5\0VS140\0"#
  '\xE017C'# -> "\0\0\0\0\5\0VS141\0"#
  '\xE017D'# -> "\0\0\0\0\5\0VS142\0"#
  '\xE017E'# -> "\0\0\0\0\5\0VS143\0"#
  '\xE017F'# -> "\0\0\0\0\5\0VS144\0"#
  '\xE0180'# -> "\0\0\0\0\5\0VS145\0"#
  '\xE0181'# -> "\0\0\0\0\5\0VS146\0"#
  '\xE0182'# -> "\0\0\0\0\5\0VS147\0"#
  '\xE0183'# -> "\0\0\0\0\5\0VS148\0"#
  '\xE0184'# -> "\0\0\0\0\5\0VS149\0"#
  '\xE0185'# -> "\0\0\0\0\5\0VS150\0"#
  '\xE0186'# -> "\0\0\0\0\5\0VS151\0"#
  '\xE0187'# -> "\0\0\0\0\5\0VS152\0"#
  '\xE0188'# -> "\0\0\0\0\5\0VS153\0"#
  '\xE0189'# -> "\0\0\0\0\5\0VS154\0"#
  '\xE018A'# -> "\0\0\0\0\5\0VS155\0"#
  '\xE018B'# -> "\0\0\0\0\5\0VS156\0"#
  '\xE018C'# -> "\0\0\0\0\5\0VS157\0"#
  '\xE018D'# -> "\0\0\0\0\5\0VS158\0"#
  '\xE018E'# -> "\0\0\0\0\5\0VS159\0"#
  '\xE018F'# -> "\0\0\0\0\5\0VS160\0"#
  '\xE0190'# -> "\0\0\0\0\5\0VS161\0"#
  '\xE0191'# -> "\0\0\0\0\5\0VS162\0"#
  '\xE0192'# -> "\0\0\0\0\5\0VS163\0"#
  '\xE0193'# -> "\0\0\0\0\5\0VS164\0"#
  '\xE0194'# -> "\0\0\0\0\5\0VS165\0"#
  '\xE0195'# -> "\0\0\0\0\5\0VS166\0"#
  '\xE0196'# -> "\0\0\0\0\5\0VS167\0"#
  '\xE0197'# -> "\0\0\0\0\5\0VS168\0"#
  '\xE0198'# -> "\0\0\0\0\5\0VS169\0"#
  '\xE0199'# -> "\0\0\0\0\5\0VS170\0"#
  '\xE019A'# -> "\0\0\0\0\5\0VS171\0"#
  '\xE019B'# -> "\0\0\0\0\5\0VS172\0"#
  '\xE019C'# -> "\0\0\0\0\5\0VS173\0"#
  '\xE019D'# -> "\0\0\0\0\5\0VS174\0"#
  '\xE019E'# -> "\0\0\0\0\5\0VS175\0"#
  '\xE019F'# -> "\0\0\0\0\5\0VS176\0"#
  '\xE01A0'# -> "\0\0\0\0\5\0VS177\0"#
  '\xE01A1'# -> "\0\0\0\0\5\0VS178\0"#
  '\xE01A2'# -> "\0\0\0\0\5\0VS179\0"#
  '\xE01A3'# -> "\0\0\0\0\5\0VS180\0"#
  '\xE01A4'# -> "\0\0\0\0\5\0VS181\0"#
  '\xE01A5'# -> "\0\0\0\0\5\0VS182\0"#
  '\xE01A6'# -> "\0\0\0\0\5\0VS183\0"#
  '\xE01A7'# -> "\0\0\0\0\5\0VS184\0"#
  '\xE01A8'# -> "\0\0\0\0\5\0VS185\0"#
  '\xE01A9'# -> "\0\0\0\0\5\0VS186\0"#
  '\xE01AA'# -> "\0\0\0\0\5\0VS187\0"#
  '\xE01AB'# -> "\0\0\0\0\5\0VS188\0"#
  '\xE01AC'# -> "\0\0\0\0\5\0VS189\0"#
  '\xE01AD'# -> "\0\0\0\0\5\0VS190\0"#
  '\xE01AE'# -> "\0\0\0\0\5\0VS191\0"#
  '\xE01AF'# -> "\0\0\0\0\5\0VS192\0"#
  '\xE01B0'# -> "\0\0\0\0\5\0VS193\0"#
  '\xE01B1'# -> "\0\0\0\0\5\0VS194\0"#
  '\xE01B2'# -> "\0\0\0\0\5\0VS195\0"#
  '\xE01B3'# -> "\0\0\0\0\5\0VS196\0"#
  '\xE01B4'# -> "\0\0\0\0\5\0VS197\0"#
  '\xE01B5'# -> "\0\0\0\0\5\0VS198\0"#
  '\xE01B6'# -> "\0\0\0\0\5\0VS199\0"#
  '\xE01B7'# -> "\0\0\0\0\5\0VS200\0"#
  '\xE01B8'# -> "\0\0\0\0\5\0VS201\0"#
  '\xE01B9'# -> "\0\0\0\0\5\0VS202\0"#
  '\xE01BA'# -> "\0\0\0\0\5\0VS203\0"#
  '\xE01BB'# -> "\0\0\0\0\5\0VS204\0"#
  '\xE01BC'# -> "\0\0\0\0\5\0VS205\0"#
  '\xE01BD'# -> "\0\0\0\0\5\0VS206\0"#
  '\xE01BE'# -> "\0\0\0\0\5\0VS207\0"#
  '\xE01BF'# -> "\0\0\0\0\5\0VS208\0"#
  '\xE01C0'# -> "\0\0\0\0\5\0VS209\0"#
  '\xE01C1'# -> "\0\0\0\0\5\0VS210\0"#
  '\xE01C2'# -> "\0\0\0\0\5\0VS211\0"#
  '\xE01C3'# -> "\0\0\0\0\5\0VS212\0"#
  '\xE01C4'# -> "\0\0\0\0\5\0VS213\0"#
  '\xE01C5'# -> "\0\0\0\0\5\0VS214\0"#
  '\xE01C6'# -> "\0\0\0\0\5\0VS215\0"#
  '\xE01C7'# -> "\0\0\0\0\5\0VS216\0"#
  '\xE01C8'# -> "\0\0\0\0\5\0VS217\0"#
  '\xE01C9'# -> "\0\0\0\0\5\0VS218\0"#
  '\xE01CA'# -> "\0\0\0\0\5\0VS219\0"#
  '\xE01CB'# -> "\0\0\0\0\5\0VS220\0"#
  '\xE01CC'# -> "\0\0\0\0\5\0VS221\0"#
  '\xE01CD'# -> "\0\0\0\0\5\0VS222\0"#
  '\xE01CE'# -> "\0\0\0\0\5\0VS223\0"#
  '\xE01CF'# -> "\0\0\0\0\5\0VS224\0"#
  '\xE01D0'# -> "\0\0\0\0\5\0VS225\0"#
  '\xE01D1'# -> "\0\0\0\0\5\0VS226\0"#
  '\xE01D2'# -> "\0\0\0\0\5\0VS227\0"#
  '\xE01D3'# -> "\0\0\0\0\5\0VS228\0"#
  '\xE01D4'# -> "\0\0\0\0\5\0VS229\0"#
  '\xE01D5'# -> "\0\0\0\0\5\0VS230\0"#
  '\xE01D6'# -> "\0\0\0\0\5\0VS231\0"#
  '\xE01D7'# -> "\0\0\0\0\5\0VS232\0"#
  '\xE01D8'# -> "\0\0\0\0\5\0VS233\0"#
  '\xE01D9'# -> "\0\0\0\0\5\0VS234\0"#
  '\xE01DA'# -> "\0\0\0\0\5\0VS235\0"#
  '\xE01DB'# -> "\0\0\0\0\5\0VS236\0"#
  '\xE01DC'# -> "\0\0\0\0\5\0VS237\0"#
  '\xE01DD'# -> "\0\0\0\0\5\0VS238\0"#
  '\xE01DE'# -> "\0\0\0\0\5\0VS239\0"#
  '\xE01DF'# -> "\0\0\0\0\5\0VS240\0"#
  '\xE01E0'# -> "\0\0\0\0\5\0VS241\0"#
  '\xE01E1'# -> "\0\0\0\0\5\0VS242\0"#
  '\xE01E2'# -> "\0\0\0\0\5\0VS243\0"#
  '\xE01E3'# -> "\0\0\0\0\5\0VS244\0"#
  '\xE01E4'# -> "\0\0\0\0\5\0VS245\0"#
  '\xE01E5'# -> "\0\0\0\0\5\0VS246\0"#
  '\xE01E6'# -> "\0\0\0\0\5\0VS247\0"#
  '\xE01E7'# -> "\0\0\0\0\5\0VS248\0"#
  '\xE01E8'# -> "\0\0\0\0\5\0VS249\0"#
  '\xE01E9'# -> "\0\0\0\0\5\0VS250\0"#
  '\xE01EA'# -> "\0\0\0\0\5\0VS251\0"#
  '\xE01EB'# -> "\0\0\0\0\5\0VS252\0"#
  '\xE01EC'# -> "\0\0\0\0\5\0VS253\0"#
  '\xE01ED'# -> "\0\0\0\0\5\0VS254\0"#
  '\xE01EE'# -> "\0\0\0\0\5\0VS255\0"#
  '\xE01EF'# -> "\0\0\0\0\5\0VS256\0"#

  _          -> "\xff"#
